//---------------Imports----------------//
import { Alligator } from "./models/Alligator.js";
import { Beaver } from "./models/Beaver.js";
import { Cat } from "./models/Cat.js";
import { Cat } from "./models/Cat.js";
import { Dog } from "./models/Dog.js";
import { Emu } from "./models/Emu.js";
import { Fox } from "./models/Fox.js";
import { Gorilla } from "./models/Gorilla.js";
import { Hawk } from "./models/Hawk.js";
import { Iguana } from "./models/Iguana.js";
import { Jackrabbit } from "./models/Jackrabbit.js";
import { Kangaroo } from "./models/Kangaroo.js";
import { Lama } from "./models/Lama.js";
import { Mouse } from "./models/Mouse.js";
import { Newt} from "./models/Newt.js";
import { Owl} from "./models/Owl.js";
import { Panther} from "./models/Panther.js";
import { Quail} from "./models/Quail.js";
import { Raccon} from "./models/Raccon.js";
import { Snake } from "./models/Snake.js";
import { Tapir } from "./models/Tapir.js";
import { Urchin } from "./models/Urchin.js";
import { Vole } from "./models/Vole.js";
import { Wallaby } from "./models/Wallaby.js";
import { Xray } from "./models/Xray.js";
import { Zebra } from "./models/Zebra.js";

// ----------Declarations of new vars inside the main---------//
let ally = new Alligator("Ally", "Green", "F", 200, 60, "big");
let beaver = new Beaver("Betsie", "Brown", "F", 20, 10, "big");
let cat = new Cat("Cara", "Orange", "F", 10, 6, "small");
let dog = new Dog("Dingo", "Catahoola", "M", 200, 5, "small");
let emu = new Emu("Edna", "White", "F", 200, 2, "small");
let fox = new Fox("Felicity", "Gray", "F", 20, 8, "small");
let gorilla = new Gorilla("Gina", "Black", "F", 200, "small");
let hawk = new Hawk("Hanna", "Brown", "F", 20, 1, "small");
let iguana = new Iguana("Irene", "Sand", "F", 20, 60, "small");
let jackrabbit = new Jackrabbit("Jennifer", "Brown", "F", 20, 1, "big");
let kangaroo = new Kangaroo("Kelly", "Sand", "F", 200, 20, "small");
let lama = new Lama("Laura", "Brown", "F", 200, 6, "small");
let mouse = new Mouse("Mary", "Gray", "F", 2, 1, "small");
let newt = new Newt("Nora", "Black", "F", 1);
let owl = new Owl("Olivia", "White with spots", "F", 20, 2, "small");
let panther = new Panther("Priscilla", "Black", "F", 200, 60, "big");
let quail = new Quail("Q", "Brown", "F", 2);
let ronnie = new Raccon("Ronnie", "Panda", "F", 40, 10, "small");
let snake = new Snake("Sam", "Coral", "M", 5, 60);
let tapir = new Tapir("Tom", "Brown", "M", 200, 5);
let urchin = new Urchin("Urkle", "Purple", "M", 200, 2, "small");
let vole = new Vole("Violet", "Black", "F", 20, 1, "small");
let wallaby = new Wallaby("Wanda", "Gray", "F", 100, 6, "small");
let xray = new Xray("Xena", "Gray", "F", 100, 6);
let zebra = new Zebra("Zuule", "White and Black", "F", 200, 6, "small");